### ISSUE TITLE
Cant create vm without template

### ISSUE THREAD

**Issue by xiaoyao9184** [dseeley/esxifree_guest#1]
error log is 
```
Traceback (most recent call last):
  File \"/home/xy/.ansible/tmp/ansible-tmp-1697442855.7487946-3807-259591959282038/AnsiballZ_esxifree_guest.py\", line 107, in <module>
    _ansiballz_main()
  File \"/home/xy/.ansible/tmp/ansible-tmp-1697442855.7487946-3807-259591959282038/AnsiballZ_esxifree_guest.py\", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File \"/home/xy/.ansible/tmp/ansible-tmp-1697442855.7487946-3807-259591959282038/AnsiballZ_esxifree_guest.py\", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.dseeley.esxifree_guest.plugins.modules.esxifree_guest', init_globals=dict(_module_fqn='ansible_collections.dseeley.esxifree_guest.plugins.modules.esxifree_guest', _modlib_path=modlib_path),
  File \"<frozen runpy>\", line 226, in run_module
  File \"<frozen runpy>\", line 98, in _run_module_code
  File \"<frozen runpy>\", line 88, in _run_code
  File \"/tmp/ansible_esxifree_guest_payload_15j3tqq3/ansible_esxifree_guest_payload.zip/ansible_collections/dseeley/esxifree_guest/plugins/modules/esxifree_guest.py\", line 1149, in <module>
  File \"/tmp/ansible_esxifree_guest_payload_15j3tqq3/ansible_esxifree_guest_payload.zip/ansible_collections/dseeley/esxifree_guest/plugins/modules/esxifree_guest.py\", line 1106, in main
  File \"/tmp/ansible_esxifree_guest_payload_15j3tqq3/ansible_esxifree_guest_payload.zip/ansible_collections/dseeley/esxifree_guest/plugins/modules/esxifree_guest.py\", line 514, in exec_command
OSError: b'(vim.fault.NotFound) {\
   faultCause = (vmodl.MethodFault) null, \
   faultMessage = <unset>\
   msg = \"Unable to find a VM corresponding to \"None\"\"\
}\
```

playbook action is
```yml
esxifree_guest:
  datastore: "datastore1"
  disks: 
  - size_gb: 1
    src:
      backing_filename: "[datastore1] Openwrt22.clone/openwrt-22.03.5-x86-64-generic-squashfs-combined-efi.vmdk"
      copy_or_move: "copy"
    type: "thin"
    volname: "thin"
  guest_id: "openwrt-clone"
  hardware:
    memory_mb: 384
    num_cpus: 1
    version: 15
  name: "openwrt-clone"
  networks:
  - networkName: "VM Network"
    virtualDev: "vmxnet3"
  state: "present"
  hostname: "esxi.lan"
  username: "root"
  password: "************"
```

i think maybe some mistake at here?
https://github.com/dseeley/esxifree_guest/blob/6c3c8df6c9fae5eaad156e33e2997310aeefbaea/plugins/modules/esxifree_guest.py#L1095

**Comment by dseeley** [comment]
Hi - There are a few yaml syntax issues with your example - not sure if these are copy/paste issues (trailing `"` after `size_gb`, `volname`, `copy_or_mov` (which should be `copy_or_move`))?

**Comment by xiaoyao9184** [comment]
@dseeley sorry about that, it was a writing error and has been corrected, because it was caused by manually converting the json printed by `ansible.builtin.debug` into yaml.

**Comment by dseeley** [comment]
OK - so it's still an issue then?  Can you let me know which version of ESXi you are using?

**Comment by xiaoyao9184** [comment]
version
```
ESXi-8.0b-21203435-standard
```

**Comment by dseeley** [comment]
Hmm, OK - I've not tested this on ESXi >7, but will have a look later on.

**Comment by dseeley** [comment]
Hi - fixed this in latest commit, however, it won't do a lot without a template to clone from.  You might also want to define `wait: false`, as it will otherwise wait for an IP to be presented, which won't happen without a base image.
